import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { MainProvider } from "@/providers/MainProvider";
import { Cart } from "@/components/cart/Cart";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body className="antialiased flex min-h-screen bg-[#00980d]">
			<MainProvider>
				<Header/>
				<div className="w-full">
					<main className="flex p-3 flex-1 min-h-screen bg-[url('/assets/bg.png')]">
						{children}
					</main>
					<Cart/>
					<Footer/>
				</div>
			</MainProvider>
		</body>
		</html>
	);
}