import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { MainProvider } from "@/providers/MainProvider";
import { Cart } from "@/components/cart/Cart";
import { MyTooltip } from "@/components/partials/Tooltip";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en" >
		<body className="flex w-full antialiased bg-[#00980d] bg-[url('/assets/bg.png')]" suppressHydrationWarning={true} >
			<MainProvider>
				<Header/>
				<main className="flex flex-col w-full min-h-screen">
					<div className="w-full p-3 min-h-screen flex-1">
						{children}
					</div>
					<Cart/>
					<Footer/>
					<MyTooltip id="tip-top" place="top" variant="dark" />
					<MyTooltip id="tip-right" place="right" variant="dark" />
				</main>
			</MainProvider>
		</body>
		</html>
	);
}